#!/bin/bash
########################################
# Set environment variables
########################################

export CGO_CFLAGS=
export CGO_LDFLAGS="-lforeman++ -lstdc++ -lalglib -lsqlite3 -lcurl -luuid -lm"

# NOTE : Enable for folly
# export CGO_LDFLAGS="$CGO_LDFLAGS -lfolly -lgflags -lglog -ljemalloc"

if [ `which python3-config` ]; then
	export CGO_CFLAGS="$CGO_CFLAGS `python3-config --includes`"
	export CGO_LDFLAGS="$CGO_LDFLAGS `python3-config --ldflags --embed`"
else
	if [ `which python-config` ]; then
		export CGO_CFLAGS="$CGO_CFLAGS `python-config --includes`"
		export CGO_LDFLAGS="$CGO_LDFLAGS `python-config --ldflags`"
	fi
fi

if [ `which uuid-config` ]; then
    CGO_CFLAGS="$CGO_CFLAGS `uuid-config --cflags`"
    CGO_LDFLAGS="$CGO_LDFLAGS `uuid-config --ldflags`"
fi

if [ `which pkg-config` ]; then
	export CGO_CFLAGS="$CGO_CFLAGS `pkg-config lua --silence-errors --cflags`"
	export CGO_LDFLAGS="$CGO_LDFLAGS `pkg-config lua --silence-errors --libs`"
fi

export CGO_CXXFLAGS="$CGO_CFLAGS -std=c++11"
