#!/bin/bash
export GOPATH=`pwd`
git pull
go get -u github.com/cybergarage/foreman-go/foreman
go get -u github.com/cybergarage/go-config/config
go get -u git.corp.cybergarage.org/kvspj/go-graphite/net/graphite
