# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Foreman-cc packages
      run: |
        sudo apt update
        sudo apt-get install -y g++ automake libboost-all-dev make pkg-config
        sudo apt-get install -y libsqlite3-dev libcurl3-dev libalglib-dev libossp-uuid-dev libpython3-all-dev

    - name: Setup Foreman-cc
      run: |
        git clone https://github.com/cybergarage/foreman-cc.git
        pushd foreman-cc
        echo `pwd`
        CFLAGS="-I`pwd`" ./configure_ubuntu
        make -j 20 check
        sudo make install
        popd

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'

    - name: Test
      run: make test
